title:        Emre Tepe | @emretepedev
email:        emretepedev@gmail.com
tagline:      The Personal Website
description:  Emre Tepe - emretepedev
author:       Emre Tepe
url:          https://emretepedev.github.io
locale:       en_US
google_site_verification:
social:
  name: Emre Tepe
  links:
    - https://twitter.com/emretepedev
    - https://www.facebook.com/emretepedev
    - https://www.linkedin.com/in/emretepedev
    - https://github.com/emretepedev
    - https://instagram.com/emretepedev
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
twitter:
  username: emretepedev
  card: summary