title:              emretepeyazilim
email:              emretepeyazilim@gmail.com
description:        Focus on Science!
author:             Emre Tepe
baseurl:            ""
url:                "https://denemejekyll.tk"