title:        Emre Tepe | @emretepedev
email:        emretepedev@gmail.com
tagline:      Web Sitenizi Oluşturun!
description:  Web Siteniz İçin Fiyat Alın Ve Bir Web Sitesi Oluşturun!
author:       Emre Tepe
url:          https://emretepedev.github.io

locale:       tr_TR
google_site_verification:
social:
  name: Emre Tepe
  links:
    - https://twitter.com/emretepedev
    - https://www.facebook.com/emretepedev
    - https://www.linkedin.com/in/emretepedev
    - https://github.com/emretepedev
    - https://instagram.com/emretepedev

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

twitter:
  username: emretepedev
  card: summary