name: cd

on:
  push:
    branches:
      - nuxt-bridge
      - main
      - master
  pull_request:
    branches:
      - nuxt-bridge
      - main
      - master

env:
  NODE_ENV: ${{ secrets.NODE_ENV }}
  SPA_NAME: ${{ secrets.SPA_NAME }}
  SPA_ORIGIN: ${{ secrets.SPA_ORIGIN }}
  SPA_URL: ${{ secrets.SPA_URL }}
  SPA_PATH: ${{ secrets.SPA_PATH }}
  GH_USERNAME: ${{ secrets.GH_USERNAME }}
  GH_PERSONAL_ACCESS_TOKEN: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
  GOOGLE_RECAPTCHA_V2_SITE_KEY: ${{ secrets.GOOGLE_RECAPTCHA_V2_SITE_KEY }}
  GOOGLE_RECAPTCHA_V3_SITE_KEY: ${{ secrets.GOOGLE_RECAPTCHA_V3_SITE_KEY }}
  GOOGLE_TAG_MANAGER_ID: ${{ secrets.GOOGLE_TAG_MANAGER_ID }}
  GOOGLE_ANALYTICS_4_ID: ${{ secrets.GOOGLE_ANALYTICS_4_ID }}
  PAGECLIP_ACTION_URL: ${{ secrets.PAGECLIP_ACTION_URL }}
  OWNER_ADDRESS: ${{ secrets.OWNER_ADDRESS }}
  TX_CONFIRMATION_BLOCKS: ${{ secrets.TX_CONFIRMATION_BLOCKS }}
  REPOSITORY_URL: ${{ secrets.REPOSITORY_URL }}
  VISITORS_BOOK_CONTRACT_ADDRESS: ${{ secrets.VISITORS_BOOK_CONTRACT_ADDRESS }}
  VISITORS_BOOK_CONTRACT_CHAIN_ID: ${{ secrets.VISITORS_BOOK_CONTRACT_CHAIN_ID }}
  VISITORS_BOOK_CONTRACT_CHAIN_NAME: ${{ secrets.VISITORS_BOOK_CONTRACT_CHAIN_NAME }}
  TEST_WEBSITE: ${{ secrets.TEST_WEBSITE }}
  LIVE: ${{ secrets.LIVE }}

jobs:
  cd:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-22.04]
        node: [18]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Verify change src files in the contracts directory
        uses: tj-actions/verify-changed-files@v9
        id: verify-changed-sol-files
        with:
          files: |
            src
            nuxt.config.ts
            package.json
            yarn.lock

      - name: Show changes
        run: |
          echo "Changed files: ${{ steps.verify-changed-files.outputs.changed_files }}"

      - name: Bump version and push tag
        id: tag_version
        uses: anothrNick/github-tag-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          DEFAULT_BUMP: none

      - name: Setup node
        uses: actions/setup-node@v3
        if: steps.verify-changed-files.outputs.files_changed == 'true'
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies with dev deps
        if: steps.verify-changed-files.outputs.files_changed == 'true'
        run: yarn install --production=false

      - name: Fetch recent contributions count
        if: steps.verify-changed-files.outputs.files_changed == 'true'
        run: yarn fetch

      - name: Build
        if: steps.verify-changed-files.outputs.files_changed == 'true'
        run: yarn build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: steps.verify-changed-files.outputs.files_changed == 'true'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./.output/public
          publish_branch: gh-pages

      - name: Create a GitHub release
        uses: softprops/action-gh-release@v1
        if: steps.verify-changed-files.outputs.files_changed == 'true'
        with:
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          tag_name: ${{ steps.tag_version.outputs.new_tag }}
