name: cd

on: [push, pull_request]

env:
  NODE_ENV: ${{ secrets.NODE_ENV }}
  SPA_NAME: ${{ secrets.SPA_NAME }}
  SPA_URL: ${{ secrets.SPA_URL }}
  GH_USERNAME: ${{ secrets.GH_USERNAME }}
  GH_PERSONAL_ACCESS_TOKEN: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
  GOOGLE_RECAPTCHA_V2_SITE_KEY: ${{ secrets.GOOGLE_RECAPTCHA_V2_SITE_KEY }}
  GOOGLE_RECAPTCHA_V3_SITE_KEY: ${{ secrets.GOOGLE_RECAPTCHA_V3_SITE_KEY }}
  GOOGLE_TAG_MANAGER_ID: ${{ secrets.GOOGLE_TAG_MANAGER_ID }}
  GOOGLE_ANALYTICS_4_ID: ${{ secrets.GOOGLE_ANALYTICS_4_ID }}
  PAGECLIP_ACTION_URL: ${{ secrets.PAGECLIP_ACTION_URL }}
  OWNER_ADDRESS: ${{ secrets.OWNER_ADDRESS }}
  TX_CONFIRMATION_BLOCKS: ${{ secrets.TX_CONFIRMATION_BLOCKS }}
  REPOSITORY_URL: ${{ secrets.REPOSITORY_URL }}

jobs:
  cd:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [16]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Bump version and push tag
        id: tag_version
        uses: anothrNick/github-tag-action@1.36.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          DEFAULT_BUMP: none

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies with dev deps
        run: yarn install --production=false

      - name: Fetch recent contributions count
        run: yarn fetch

      - name: Generate
        run: yarn generate

      - name: Install dependencies
        run: yarn install

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: gh-pages

      - name: Create a GitHub release
        uses: softprops/action-gh-release@v1
        with:
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          tag_name: ${{ steps.tag_version.outputs.new_tag }}
