name: cd

on: [push, pull_request]

env:
    NODE_ENV: ${{ secrets.NODE_ENV }}
    SPA_NAME: ${{ secrets.SPA_NAME }}
    SPA_URL: ${{ secrets.SPA_URL }}
    GOOGLE_RECAPTCHA_SITE_KEY: ${{ secrets.GOOGLE_RECAPTCHA_SITE_KEY }}
    GOOGLE_ANALYTICS_ID: ${{ secrets.GOOGLE_ANALYTICS_ID }}

jobs:
    cd:
        runs-on: ${{ matrix.os }}

        strategy:
            matrix:
                os: [ubuntu-latest]
                node: [14]

        steps:
            - name: Checkout
              uses: actions/checkout@master

            - name: Setup node env
              uses: actions/setup-node@v2.1.2
              with:
                  node-version: ${{ matrix.node }}

            - name: Install dependencies
              run: yarn

            - name: Generate
              run: yarn generate
              env:
                  NODE_ENV: ${{ secrets.NODE_ENV }}
                  SPA_NAME: ${{ secrets.SPA_NAME }}
                  SPA_URL: ${{ secrets.SPA_URL }}
                  GOOGLE_RECAPTCHA_SITE_KEY: ${{ secrets.GOOGLE_RECAPTCHA_SITE_KEY }}
                  GOOGLE_ANALYTICS_ID: ${{ secrets.GOOGLE_ANALYTICS_ID }}

            - name: Deploy
              uses: peaceiris/actions-gh-pages@v3
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: ./dist
